using System;
using System.Collections;
using System.ComponentModel;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using DGCore.DGVList;
using DGCore.Sql;
using DGCore.UserSettings;
using DGView.Views;

namespace DGView.ViewModels
{
    public partial class DataGridViewModel : DependencyObject, INotifyPropertyChanged, IComponent, IUserSettingSupport<DGV>
    {
        public const bool AUTOGENERATE_COLUMNS = false;

        public DataGridView View { get; }
        public DataGrid DGControl => View.DataGrid;
        private string LayoutId { get; set; }
        private string StartUpParameters { get; set; }
        private string _lastAppliedLayoutName { get; set; }
        // private DataSourceBase DataSource { get; set; }
        // public new DGCore.DGVList.IDGVList DataSource => base.DataSource == null ? null : (DGCore.DGVList.IDGVList)base.DataSource;
        // public IDGVList DataSource { get; set; }
        public IDGVList Data;

        private DataGridColumn[] VisibleColumns;


        public DataGridViewModel(DataGridView view)
        {
            View = view;
            InitCommands();
            DGControl.AutoGeneratedColumns += DGControl_AutoGeneratedColumns;
        }

        private void DGControl_AutoGeneratedColumns(object sender, EventArgs e)
        {
            DGControl.AutoGeneratedColumns -= DGControl_AutoGeneratedColumns;
            foreach (var c in DGControl.Columns)
            {

            }
        }

        public void Bind(DataSourceBase ds, string layoutID, string startUpParameters, string startUpLayoutName, DGV settings)
        {
            LayoutId = layoutID;
            StartUpParameters = startUpParameters;

            DGCore.Misc.DependentObjectManager.Bind(ds, this); // Register object    

            var listType = typeof(DGVList<>).MakeGenericType(ds.ItemType);
            // var dataSource = (IDGVList)Activator.CreateInstance(listType, ds, (Func<DGCore.Utils.DGVColumnHelper[]>)GetColumnHelpers);
            var dataSource = (IDGVList)Activator.CreateInstance(listType, ds, null);
            Data = dataSource;
            DGControl.ItemsSource = (IEnumerable)Data;

            Unwire();
            Wire();
            SetEnabled(false);

            if (!AUTOGENERATE_COLUMNS)
                Helpers.DataGridHelper.GenerateColumns(this);
            VisibleColumns = Helpers.DataGridHelper.GetColumnsInDisplayOrder(DGControl, true);

            if (!string.IsNullOrEmpty(startUpLayoutName))
                _lastAppliedLayoutName = startUpLayoutName;

            if (settings != null)
                ((IUserSettingSupport<DGV>)this).SetSetting(settings);
            else
                UserSettingsUtils.Init(this, startUpLayoutName);

            Task.Factory.StartNew(() =>
            {
                Data.UnderlyingData.GetData(false);
            });
        }

        #region ===========  INotifyPropertyChanged  ==============
        public event PropertyChangedEventHandler PropertyChanged;

        private void OnPropertiesChanged(params string[] propertyNames)
        {
            foreach (var propertyName in propertyNames)
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
        #endregion

        #region ===========  IComponent  ==============
        private bool _disposing = false;
        public void Dispose()
        {
            if (_disposing)
                return;

            _disposing = true;
            Unwire();
            // DataSource.Dispose();
            Data?.Dispose();
            Disposed?.Invoke(this, new EventArgs());
            Data = null;
        }

        public ISite Site { get; set; }
        public event EventHandler Disposed;
        #endregion

        #region ========   IUserSettingSupport<DGV>  ========
        public string _layoutID;
        internal const string UserSettingsKind = "DGV_Setting";

        public string SettingKind => UserSettingsKind;
        public string SettingKey => _layoutID;
        public DGV GetSettings()
        {
            var o = new DGV
            {
                /*WhereFilter = ((IUserSettingSupport<List<Filter>>)DataSource.WhereFilter)?.GetSettings(),
                FilterByValue = ((IUserSettingSupport<List<Filter>>)DataSource.FilterByValue)?.GetSettings(),
                ShowTotalRow = DataSource.ShowTotalRow,
                ExpandedGroupLevel = DataSource.ExpandedGroupLevel,
                ShowGroupsOfUpperLevels = DataSource.ShowGroupsOfUpperLevels,
                BaseFont = this.Font,
                IsGridVisible = this._IsGridVisible,
                CellViewMode = this._CellViewMode,
                TextFastFilter = DataSource.TextFastFilter*/
            };
            // ApplyColumnLayout(o);
            return o;
        }

        public DGV GetBlankSetting()
        {
            // Utils.Dgv.EndEdit(this);
            /*DataSource.ResetSettings();
            Font = _startupFont;
            CellBorderStyle = DataGridViewCellBorderStyle.Single; // For _IsGridVisible
            _CellViewMode = Enums.DGCellViewMode.OneRow;

            // For AllColumns
            _allValidColumnNames = Columns.Cast<DataGridViewColumn>()
                .Where(col => !string.IsNullOrEmpty(col.DataPropertyName) && !col.DataPropertyName.Contains('.'))
                .Select(col => col.DataPropertyName).ToList();

            ResizeColumnWidth(); // !!! Before SaveColumnInfo*/
            return ((IUserSettingSupport<DGV>)this).GetSettings();
        }

        public void SetSetting(DGV settings)
        {
            // throw new NotImplementedException();
        }
        #endregion

        #region =====================
        private void Wire() => Data.DataStateChanged += DataSource_DataStateChanged;

        private void Unwire()
        {
            if (Data != null)
                Data.DataStateChanged -= DataSource_DataStateChanged;
        }
        private void DataSource_DataStateChanged(object sender, DataSourceBase.SqlDataEventArgs e)
        {
            switch (e.EventKind)
            {
                case DataSourceBase.DataEventKind.Loaded:
                    // Run in WPF thread
                    DGControl.Dispatcher.BeginInvoke(new Action(() =>
                    {
                        SetEnabled(true);
                        Data.RefreshData();
                    }));
                    // DataSource_Loaded();
                    break;
                case DataSourceBase.DataEventKind.BeforeRefresh:
                    // DataSource_BeforeRefresh();
                    break;
                case DataSourceBase.DataEventKind.Refreshed:
                    // DataSource_AfterRefresh();
                    break;
            }

        }

        private void SetEnabled(bool isEnabled)
        {
            View.CommandBar.IsEnabled = isEnabled;
            DGControl.IsEnabled = isEnabled;
        }

        #endregion
    }
}
